### ISSUE TITLE
Make this ready to use without it's intro locationTrivia-DataStore

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/locationTrivia-DataStoreRelationships#4]
We are no-longer going to be using the locationTrivia-DataStore so make sure this can stand on it's own.

Maybe grab things from the [old lab](https://github.com/learn-co-curriculum/locationTrivia-DataStore)

**Comment by markedwardmurray** [comment]
resolved by commits leading up to 1bcfa7d6c4f8bca12c190bd22058d7e500a53099
